# Levels for logging outputs
# CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
LOG_LVL: "INFO"
LOG_TO_CONSOLE: True
LOG_TO_FILE: True

# Discord Bot
BOT_TOKEN: ""
DEFAULT_PREFIX: "!"
BOT_DESCRIPTION: ""
# Activities
# playing, streaming, listening, watching
BOT_ACTIVITY: ""
ACTIVITY_MESSAGE: ""
BOT_OWNERS: []

# Webhook Cog
HOOK_NAME: ""

# Postgres Database
DB_USER: ""
DB_PASSWORD: ""
DB_IP: "127.0.0.1"
DB_PORT: "5432"
DB_NAME: ""

# Lavalink Server
LAVALINK_IP: "127.0.0.1"
LAVALINK_PORT: 2333
LAVALINK_PASSWORD: ""