# Levels for logging outputs
# CRITICAL
# ERROR
# WARNING
# INFO
# DEBUG
# NOTSET
LOG_LVL: "WARNING"

# Discord Bot
BOT_TOKEN: ""
DEFAULT_PREFIX: "!"
BOT_DESCRIPTION: ""
BOT_PRESENCE: ""
BOT_OWNER: 

# Webhook Cog
HOOK_NAME: ""

# PostgreSQL Database
DB_USER: ""
DB_PASSWORD: ""
DB_IP: "127.0.0.1"
DB_PORT: "5432"
DB_NAME: ""